/*Creating tables*/
create USER DBAINTERVENTION IDENTIFIED BY root;
grant ALL PRIVILEGES TO DBAINTERVENTION;


drop table INTERVENANTS;
drop table INTERVENTIONS;
drop table Vehicule;
drop table Marque;
drop table models;
drop table EMPLOYE;
drop table Client;

CREATE TABLE Client(
        NUMCLIENT NUMBER(20) Primary Key,
        CIV char(3),
        PRENOMCLIENT char(20),
        NOMCLIENT char(20),
        DATENAISSANCE date,
        ADDRESSE char(100),
        TELPROF char(12),
        TELPREV char(12),
        FAX char(12),
        CHECK(CIV IN ('M.','Mle','Mme'))
);


CREATE TABLE Employe(
        NUMEMPLOYE NUMBER(20) Primary Key,
        NOMEMP char(20),
        PRENOMEMP char(20),
        CATEGORIE char(15),
        SALAIRE number(10,5),
        CHECK(CATEGORIE IN ('Mécanicien','Assistant'))
);

CREATE TABLE Marque(
        NUMMARQUE NUMBER(20) Primary Key,
        MARQUE char(20),
        PAY char(20)
);

CREATE TABLE MODELE(
        NUMMODELE NUMBER(20) Primary Key,
        NUMMARQUE NUMBER(20),
        CONSTRAINT NMMR_MO FOREIGN KEY (NUMMARQUE) References MARQUE(NUMMARQUE),
        MODELE char(20)
);

CREATE TABLE Vehicule(
        NUMVEHICULE NUMBER(20) Primary Key,
        NUMCLIENT NUMBER(20),
        CONSTRAINT NMC_VH FOREIGN Key (NUMCLIENT) References Client(NUMCLIENT),
        NUMMODELE NUMBER(20),      
        CONSTRAINT NMMO_VH FOREIGN Key (NUMMODELE) References MODELE(NUMMODELE),
        MODELE char(20),
        Annee NUMBER
);

CREATE TABLE INTERVENTIONS(
        NUMINTERVENTION NUMBER(20) Primary Key,
        NUMVEHICULE NUMBER(20),
        CONSTRAINT NMVH_INT FOREIGN Key (NUMVEHICULE) References Vehicule(NUMVEHICULE) ON DELETE SET NULL,
        TYPEINTERVENTION char(20),
        DATEDEBINTERV date,
        DATEFININTERV date,
        COUNTINTERV number(10,5 )
);

CREATE TABLE INTERVENANTS(
        NUMINTERVENTION NUMBER(20),
        NUMEMPLOYE NUMBER(20),
        CONSTRAINT NMINT_INTER FOREIGN Key (NUMINTERVENTION) References INTERVENTIONS(NUMINTERVENTION),
        CONSTRAINT NME_INTER FOREIGN Key (NUMEMPLOYE) References Employe(NUMEMPLOYE),   
        DATEDEB date,
        DATEFIN date
);

/* LDD */

/* Add attribute DATEINSTALLATION to table EMPLOYE and MODIFY on it*/

ALTER TABLE Employe ADD (DATEINSTALLATION date NOT NULL);
ALTER TABLE Employe MODIFY (CATEGORIE NOT NULL);
ALTER TABLE Employe MODIFY (SALAIRE NOT NULL);

/* Modify length of some attributes */

ALTER TABLE Employe MODIFY PRENOMEMP CHAR(50);
ALTER TABLE Employe MODIFY PRENOMEMP CHAR(15);
ALTER TABLE Employe DROP COLUMN DATEINSTALLATION;

/* Rename a table */
ALTER TABLE Client RENAME COLUMN ADDRESSE TO ADDRESSECLIENT;

/* make a condition to date in INTERVENTION */
ALTER TABLE INTERVENTIONS ADD CONSTRAINT check_date CHECK(DATEDEBINTERV<DATEFININTERV);

/* LMD */

/* executing file insert.sql */
@insert.sql

/* ADD 5000 DA to an employee BADI Hatem*/
UPDATE Employe SET SALAIRE = SALAIRE + 5000 WHERE PRENOMEMP = 'BADI' and NOMEMP = 'Hatem';

/* Add 5 days to start day of february INTERVENTIONS */
ALTER TABLE INTERVENTIONS DISABLE CONSTRAINT check_date; 
UPDATE INTERVENTIONS SET DATEDEBINTERV = DATEDEBINTERV + 5 WHERE EXTRACT(MONTH FROM DATEDEBINTERV) = 2;
ALTER TABLE INTERVENTIONS ENABLE CONSTRAINT check_date;

/* Delete all models of series 6 */
ALTER TABLE INTERVENTIONS DISABLE CONSTRAINT NMVH_INT;
ALTER TABLE INTERVENANTS DISABLE CONSTRAINT NMINT_INTER;
DELETE FROM VEHICULE WHERE NUMMODELE IN (SELECT NUMMODELE FROM MODELE WHERE MODELE = 'Serie 5');
DELETE FROM INTERVENTIONS WHERE NUMVEHICULE NOT IN (SELECT NUMVEHICULE FROM VEHICULE);
DELETE FROM INTERVENANTS WHERE NUMINTERVENTION NOT IN (SELECT NUMINTERVENTION  FROM INTERVENTIONS);
ALTER TABLE INTERVENTIONS ENABLE CONSTRAINT NMVH_INT;
ALTER TABLE INTERVENANTS ENABLE CONSTRAINT NMINT_INTER;

UPDATE EMPLOYE SET SALAIRE