/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces.employe;
import javax.swing.*;

import database.OracleClient;

import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
/**
 *
 * @author LENOVO IP330
 */
public class DivEmp extends javax.swing.JPanel {

    /**
     * Creates new form DivEmp
     */
	OracleClient dbmServer; 
    public DivEmp(OracleClient dbmServer) {
    	this.dbmServer = dbmServer;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	JPanel panel = new JPanel();
    	eName = new JLabel();
    	eLName = new JLabel();
    	eID = new JLabel();
    	eINV = new JLabel();
    	eSal = new JLabel();
    	eCAT = new JLabel();

    	setBackground(new java.awt.Color(34, 36, 42));
    	setForeground(new java.awt.Color(255, 255, 255));
    	setToolTipText("");

    	eName.setFont(new java.awt.Font("Roboto", 0, 20));
    	eName.setForeground(new java.awt.Color(255, 255, 255));
    	eName.setText("eName");
    	eName.setPreferredSize(new Dimension(150, 60));


    	eLName.setFont(new java.awt.Font("Roboto", 0, 20));
    	eLName.setForeground(new java.awt.Color(255, 255, 255));
    	eLName.setText("eLName");
    	eLName.setPreferredSize(new Dimension(150, 60));

    	eID.setFont(new java.awt.Font("Roboto", 0, 20));
    	eID.setForeground(new java.awt.Color(255, 255, 255));
    	eID.setText("eID");
    	eID.setPreferredSize(new Dimension(150, 60));

    	eINV.setFont(new java.awt.Font("Roboto", 0, 20));
    	eINV.setForeground(new java.awt.Color(255, 255, 255));
    	eINV.setText("eINV");
    	eINV.setPreferredSize(new Dimension(150, 60));

    	eSal.setFont(new java.awt.Font("Roboto", 0, 20));
    	eSal.setForeground(new java.awt.Color(255, 255, 255));
    	eSal.setText("eSal");
    	eSal.setPreferredSize(new Dimension(150, 60));
    	eSal.setToolTipText("Add value to salary");
    	eSal.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {

                // Create a new JOptionPane.
                JOptionPane optionPane = new JOptionPane("Enter new value:");	
                // Show the JOptionPane.
                
                String newValue = optionPane.showInputDialog("Enter new value:");
                if (newValue != null) {
                	try {
	                	eSal.setText(( Float.parseFloat(eSal.getText()) + Float.parseFloat(newValue))+"");
	                	dbmServer.updateSalaryValue(Float.parseFloat(eSal.getText()), Integer.parseInt(eID.getText()));
                	}
                	catch(Exception error) {
                		// Pop alert 
                		JOptionPane.showMessageDialog(null, "Invalide type ! Please enter a number.", "Warning", JOptionPane.WARNING_MESSAGE);
                	}
                }

                // Get the new value from the JOptionPane.
       

                // Set the text of the button to the new value.
            }
            public void mouseEntered(MouseEvent e) {
                eSal.setForeground(Color.RED); // set foreground color to red when mouse enters
            }
            public void mouseExited(MouseEvent e) {
                eSal.setForeground(Color.WHITE); // set foreground color back to black when mouse exits
            }
        });

    	eCAT.setFont(new java.awt.Font("Roboto", 0, 20));
    	eCAT.setForeground(new java.awt.Color(255, 255, 255));
    	eCAT.setText("eCAT");
    	eCAT.setPreferredSize(new Dimension(150, 60));


    	JPanel mainPanel = new JPanel();


    	GridLayout gpx = new GridLayout(1, 6, 50, 60); // increased gap to 50 pixels
    	mainPanel.setLayout(gpx);
    	mainPanel.setAlignmentX(LEFT_ALIGNMENT);
    	mainPanel.setBackground(new Color(34, 36, 42));
    	mainPanel.setSize(1030, 224);
    	mainPanel.add(eName);
    	mainPanel.add(eLName);
    	mainPanel.add(eID);
    	mainPanel.add(eINV);
    	mainPanel.add(eSal);
    	mainPanel.add(eCAT);
    	mainPanel.setBorder(BorderFactory.createMatteBorder(0,0,1,0, new Color(216,216,216)));

    	this.setLayout(new BorderLayout());

    	this.add(mainPanel, BorderLayout.WEST);
 
    }// </editor-fold>//GEN-END:initComponents


    private Dimension Dimension(int i, int j) {
		// TODO Auto-generated method stub
		return null;
	}


	// Variables declaration - do not modify//GEN-BEGIN:variables
    protected JLabel eCAT;
    protected JLabel eID;
    protected JLabel eINV;
    protected JLabel eLName;
    protected JLabel eName;
    protected JLabel eSal;
    // End of variables declaration//GEN-END:variables
}
