/*
à * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces.intervention;
import javax.swing.*;

import database.OracleClient;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
/**
 *
 * @author LENOVO IP330
 */
public class DivInterv extends javax.swing.JPanel {

    /**
     * Creates new form divEmp
     */
	OracleClient dbmServer; 
    public DivInterv() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	JPanel panel = new JPanel();

    	eName = new JLabel();
    	eInterv = new JLabel();
    	eIntervType = new JLabel();
    	eIntervStartDate = new JLabel();
    	eIntervLastDate = new JLabel();
    	eCar = new JLabel();
    	eDelete = new JButton();

    	setBackground(new java.awt.Color(34, 36, 42));
    	setForeground(new java.awt.Color(255, 255, 255));
    	setToolTipText("");

    	eName.setFont(new java.awt.Font("Roboto", 0, 20));
    	eName.setForeground(new java.awt.Color(255, 255, 255));
    	eName.setText("eName");
    	eName.setPreferredSize(new Dimension(150, 50));


    	eInterv.setFont(new java.awt.Font("Roboto", 0, 20));
    	eInterv.setForeground(new java.awt.Color(255, 255, 255));
    	eInterv.setText("eInterv");
    	eInterv.setPreferredSize(new Dimension(150, 50));

    	eIntervType.setFont(new java.awt.Font("Roboto", 0, 20));
    	eIntervType.setForeground(new java.awt.Color(255, 255, 255));
    	eIntervType.setText("eIntervType");
    	eIntervType.setPreferredSize(new Dimension(150, 50));

    	eIntervStartDate.setFont(new java.awt.Font("Roboto", 0, 20));
    	eIntervStartDate.setForeground(new java.awt.Color(255, 255, 255));
    	eIntervStartDate.setText("eIntervStartDate");
    	eIntervStartDate.setPreferredSize(new Dimension(150, 50));

    	eIntervLastDate.setFont(new java.awt.Font("Roboto", 0, 20));
    	eIntervLastDate.setForeground(new java.awt.Color(255, 255, 255));
    	eIntervLastDate.setText("eIntervLastDate");
    	eIntervLastDate.setPreferredSize(new Dimension(150, 50));
    	eIntervLastDate.setToolTipText("Add value to salary");
    	eIntervLastDate.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {

                // Create a new JOptionPane.
                JOptionPane optionPane = new JOptionPane("Enter new value:");	
                JTextField text = new JTextField();
                // Show the JOptionPane.
                String newValue = optionPane.showInputDialog("Enter new value:");
                if (newValue != null && newValue.matches("[0-9]{4}-[0-9]{2}-[0-9]{2}")) {
                	eIntervLastDate.setText(newValue);
                	dbmServer.updateLastDate(newValue,Integer.parseInt(eInterv.getText()));
                	reupdatePanel(true);
                	//dbmServer.updateIntervLastDatearyValue(Float.parseFloat(eIntervLastDate.getText()), Integer.parseInt(eIntervType.getText()));
                }

                // Get the new value from the JOptionPane.
       

                // Set the text of the button to the new value.
            }
            public void mouseEntered(MouseEvent e) {
                eIntervLastDate.setForeground(Color.RED); // set foreground color to red when mouse enters
            }
            public void mouseExited(MouseEvent e) {
                eIntervLastDate.setForeground(Color.WHITE); // set foreground color back to black when mouse exits
            }
        });

    	eCar.setFont(new java.awt.Font("Roboto", 0, 20));
    	eCar.setForeground(new java.awt.Color(255, 255, 255));
    	eCar.setText("eCar");
    	eCar.setPreferredSize(new Dimension(150, 50));

    	eDelete.setBackground(Color.RED);
    	eDelete.setSize(20,20);
    	eDelete.setText("X");
    	eDelete.setForeground(Color.WHITE);
    	eDelete.setBorder(null);
    	eDelete.addActionListener(new ActionListener() {
    		public void actionPerformed(ActionEvent e) {
    			setToNothing();
    		}
    		
    	});
    	
    	JPanel mainPanel = new JPanel();


    	GridLayout gpx = new GridLayout(1, 6, 50, 60); // increased gap to 50 pixels
    	mainPanel.setLayout(gpx);
    	mainPanel.setAlignmentX(LEFT_ALIGNMENT);
    	mainPanel.setBackground(new Color(34, 36, 42));
    	mainPanel.setSize(1030, 224);
    	mainPanel.add(eName);
    	mainPanel.add(eInterv);
    	mainPanel.add(eIntervType);
    	mainPanel.add(eIntervStartDate);
    	mainPanel.add(eIntervLastDate);
    	mainPanel.add(eCar);
    	mainPanel.setBorder(BorderFactory.createMatteBorder(0,0,1,0, new Color(216,216,216)));

    	this.setLayout(new BorderLayout());

    	this.add(mainPanel, BorderLayout.WEST);
 
    }// </editor-fold>//GEN-END:initComponents


    protected void setToNothing() {
		this.setVisible(false);
		
	}

	private Dimension Dimension(int i, int j) {
		// TODO Auto-generated method stub
		return null;
	}
    public void reupdatePanel(boolean stauts) {
    	
    }
    public void setServer(OracleClient dbmServer) {
    	this.dbmServer = dbmServer;
    }
	// Variables declaration - do not modify//GEN-BEGIN:variables
    protected JLabel eCar;
    protected JLabel eIntervType;
    protected JLabel eIntervStartDate;
    protected JLabel eInterv;
    protected JLabel eName;
    protected JLabel eIntervLastDate;
    protected JButton eDelete;
    // End of variables declaration//GEN-END:variables
}
